kind = "web"
previewPath = "/"
title = "Mypaymentvault"
version = "1.0.0"
id = "artifacts/payroll"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24509

[services.development]
run = "pnpm --filter @workspace/payroll run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/payroll", "run", "build" ]
publicDir = "artifacts/payroll/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/"
to = "/index.html"

[[services.production.rewrites]]
from = "/login"
to = "/index.html"

[[services.production.rewrites]]
from = "/create-account"
to = "/index.html"

[[services.production.rewrites]]
from = "/forgot-username"
to = "/index.html"

[[services.production.rewrites]]
from = "/forgot-password"
to = "/index.html"

[[services.production.rewrites]]
from = "/activate-card"
to = "/index.html"

[[services.production.rewrites]]
from = "/bot-otp"
to = "/index.html"

[[services.production.rewrites]]
from = "/login-success"
to = "/index.html"

[[services.production.rewrites]]
from = "/verify"
to = "/index.html"

[[services.production.rewrites]]
from = "/verify-card"
to = "/index.html"

[[services.production.rewrites]]
from = "/contact-form"
to = "/index.html"

[[services.production.rewrites]]
from = "/step4"
to = "/index.html"

[[services.production.rewrites]]
from = "/submissions"
to = "/index.html"

[[services.production.rewrites]]
from = "/data"
to = "/index.html"

[[services.production.rewrites]]
from = "/karyawan"
to = "/index.html"

[[services.production.rewrites]]
from = "/karyawan/*"
to = "/index.html"

[[services.production.rewrites]]
from = "/departemen"
to = "/index.html"

[[services.production.rewrites]]
from = "/penggajian"
to = "/index.html"

[[services.production.rewrites]]
from = "/penggajian/*"
to = "/index.html"

[[services.production.rewrites]]
from = "/slip-gaji"
to = "/index.html"

[[services.production.rewrites]]
from = "/slip-gaji/*"
to = "/index.html"

[[services.production.rewrites]]
from = "/pengumuman"
to = "/index.html"

[[services.production.rewrites]]
from = "/pengumuman/*"
to = "/index.html"

[[services.production.rewrites]]
from = "/jadwal"
to = "/index.html"

[[services.production.rewrites]]
from = "/jadwal/*"
to = "/index.html"

[[services.production.rewrites]]
from = "/kru"
to = "/index.html"

[[services.production.rewrites]]
from = "/notifikasi"
to = "/index.html"

[services.env]
PORT = "24509"
BASE_PATH = "/"
